# Generated by Django 4.1 on 2022-08-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('profesion', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
